version: 0.2

phases:
  build:
    commands:
     - yes | sdkmanager --licenses
      - chmod +x gradlew
      - ./gradlew assembleDebug
artifacts:
  files:
    - app/build/outputs/apk/app-debug.apk
